require 'csv'
require 'date'
require 'nokogiri'
require 'open-uri'
require 'pry'
require 'terminal-table'

require_relative './canadian_mergers/version'
require_relative './canadian_mergers/cli'
require_relative './canadian_mergers/merger_list.rb'
require_relative './canadian_mergers/merger.rb'
require_relative './canadian_mergers/scrape.rb'
